export default {
    products: [
        {
            _id: '1',
            name :'Full zip runner shirt',
            image: '/images/product-1.webp',
            price: 60,
            brand: 'ZARA',
            rating: 2.5,
            numReviews: 5,
            countInStock: 6,
        },
        {
            _id: '2',
            name :'Full zip runner shirt',
            image: '/images/product-2.jpg',
            price: 60,
            brand: 'ZARA',
            rating: 4.0,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '3',
            name :'Full zip runner shirt',
            image: '/images/product-3.webp',
            price: 60,
            brand: 'ZARA',
            rating: 4,
            numReviews: 7,
            countInStock: 6,
        },
        {
            _id: '4',
            name :'Full zip runner shirt',
            image: '/images/product-4.webp',
            price: 60,
            brand: 'ZARA',
            rating: 3.5,
            numReviews: 25,
            countInStock: 6,
        },
        {
            _id: '5',
            name :'Full zip runner shirt',
            image: '/images/product-5.webp',
            price: 60,
            brand: 'ZARA',
            rating: 2.0,
            numReviews: 56,
            countInStock: 6,
        },
        {
            _id: '6',
            name :'Full zip runner shirt',
            image: '/images/product-6.webp',
            price: 60,
            brand: 'ZARA',
            rating: 5.0,
            numReviews: 45,
            countInStock: 6,
        },
    ],
};