export default {
    products: [
        {
            _id: '111111111111111111111111',
            name :'Relentless Shark',
            image: '/images/product-1.webp',
            price: 90,
            brand: 'ZARA',
            rating: 2.5,
            numReviews: 5,
            countInStock: 6,
            description:'this a full slive shirt',
        },
        {
            _id: '222222222222222222222222',
            name :'Tom And Jerry',
            image: '/images/product-2.jpg',
            price: 50,
            brand: 'H&M',
            rating: 4.0,
            numReviews: 10,
            countInStock: 6,
            description:'this a full slive shirt',
        },
        {
            _id: '333333333333333333333333',
            name :' My Anxiety Racing',
            image: '/images/product-3.webp',
            price: 70,
            brand: 'Crocodile',
            rating: 4,
            numReviews: 7,
            countInStock: 6,
            description:'this a full slive shirt',
        },
        {
            _id: '444444444444444444444444',
            name :'Solids: Light Grey',
            image: '/images/product-4.webp',
            price: 99,
            brand: 'LaCoste',
            rating: 3.5,
            numReviews: 25,
            countInStock: 6,
            description:'this a full slive shirt',
        },
        {
            _id: '555555555555555555555555',
            name :'Solids: Mid Black',
            image: '/images/product-5.webp',
            price: 120,
            brand: 'Addidas',
            rating: 2.0,
            numReviews: 56,
            countInStock: 6,
            description:'this a full slive shirt',
        },
        {
            _id: '666666666666666666666666',
            name :'Solids: Mid Blue',
            image: '/images/product-6.webp',
            price: 129,
            brand: 'Jack And Jones',
            rating: 5.0,
            numReviews: 45,
            countInStock: 6,
            description:'this a full slive shirt',
        },
    ],
};